# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64bd165b39c2efec968260aa1813827b255faaa195aacc8765eab6d862cbfc93a68cb50be839ab0ec2e75990557339ac5f50a1dfc1f501343dc7825dd1aea762

test:
  secret_key_base: da76000cc60d4e56a13cba3f98eb8c31aa4ff3fbac82d273a67e40b8ed6409290e2a4b08679e8ef358cc3fbfbc6151f01ad11e7130c2b2c55ee4d4bd91a8360c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
